version: '3'
services:
  caddy:
    image: micro-caddy:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  front-end:
    image: project-front-end:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - target: 8082
        published: 8082
        mode: host
    environment:
      BROKER_URL: "http://backend"
    
  broker-service:
    image: project-broker-service:latest
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: project-listener-service:latest
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: project-authentication-service:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: project-logger-service:latest
    deploy:
      mode: replicated
      replicas: 1

  mailer-service:
    image: project-mailer-service:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: "john.smith@example.com"
  
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    deploy:
      mode: global
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - target: 8025
        published: 8025
        mode: host
    deploy:
      mode: global
  
  mongo:
    image: 'mongo:4.2.17-bionic'
    ports:
      - target: 27017
        published: 27017
        mode: host
    deploy:
      mode: global
    environment:
      MONGODB_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: 'postgres:14.2'
    ports:
      - target: 5432
        published: 5432
        mode: host
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config: